import { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Ashwagandha Vitality Capsules',
    description: 'Pure organic Ashwagandha root extract to help reduce stress and boost energy levels.',
    price: 24.99,
    category: 'Wellness',
    image: 'https://picsum.photos/seed/ashwagandha/600/800',
    benefits: ['Stress Relief', 'Energy Boost', 'Improved Focus'],
    ingredients: ['Organic Ashwagandha Root', 'Vegetable Cellulose Capsule'],
  },
  {
    id: '2',
    name: 'Turmeric Glow Face Oil',
    description: 'A rejuvenating blend of turmeric and essential oils for a natural, radiant complexion.',
    price: 32.50,
    category: 'Skincare',
    image: 'https://picsum.photos/seed/turmeric/600/800',
    benefits: ['Anti-inflammatory', 'Brightening', 'Hydrating'],
    ingredients: ['Turmeric Oil', 'Jojoba Oil', 'Vitamin E'],
  },
  {
    id: '3',
    name: 'Zen Morning Herbal Tea',
    description: 'A calming blend of chamomile, lavender, and lemon balm for a peaceful start to your day.',
    price: 18.00,
    category: 'Tea',
    image: 'https://picsum.photos/seed/herbaltea/600/800',
    benefits: ['Calming', 'Digestive Support', 'Antioxidant Rich'],
    ingredients: ['Chamomile', 'Lavender', 'Lemon Balm', 'Peppermint'],
  },
  {
    id: '4',
    name: 'Elderberry Immune Syrup',
    description: 'Potent elderberry extract fortified with zinc and vitamin C for year-round immune support.',
    price: 21.99,
    category: 'Immunity',
    image: 'https://picsum.photos/seed/elderberry/600/800',
    benefits: ['Immune Support', 'Antioxidant', 'Great Taste'],
    ingredients: ['Elderberry Extract', 'Honey', 'Vitamin C', 'Zinc'],
  },
  {
    id: '5',
    name: 'Moringa Superfood Powder',
    description: 'Nutrient-dense moringa leaf powder, perfect for smoothies and healthy recipes.',
    price: 15.50,
    category: 'Wellness',
    image: 'https://picsum.photos/seed/moringa/600/800',
    benefits: ['Nutrient Rich', 'Detoxifying', 'Metabolism Boost'],
    ingredients: ['100% Organic Moringa Leaf Powder'],
  },
  {
    id: '6',
    name: 'Rosewater Refreshing Mist',
    description: 'Pure steam-distilled rosewater to hydrate and soothe your skin throughout the day.',
    price: 14.00,
    category: 'Skincare',
    image: 'https://picsum.photos/seed/rosewater/600/800',
    benefits: ['Hydrating', 'Soothing', 'Natural Fragrance'],
    ingredients: ['Pure Rosewater', 'Aloe Vera Extract'],
  },
];
